name: Unzip Zino

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files (debug)
        run: ls -R

      - name: Unzip zino.1.2.0.zip
        run: |
          unzip zino.1.2.0.zip -d zino_descompactado
          ls -R zino_descompactado

      - name: Commit unzipped files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Descompacta zino.1.2.0.zip automaticamente" || echo "Nada para commitar"
          git push
